name = "MermaidCallGraph"
uuid = "7b7e2762-91da-41e0-bafb-402c485bb3fe"
authors = ["t-garin"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
